### PR TITLE
Posts - Rendering the posts from the Database/JSON file to Buy In Per…

### PR DESCRIPTION
**Pull request by hasansaad1**
…son page.

relates #11 , wrothe the code that renders the posts with css.

### CODE REVIEW

**Comment by Karyum** [comment]
@hasansaad1 who ever wasn't working with you on this should review this before me and @claireinez

**Review by MarlenAw — APPROVED** [review]

**Comment by hasansaad1** [comment]
@ionush @SamiSha99  Please check the code before them merging it if you have any ideas that we can change :smile: , we're waiting for it to be merged.

**Review by nj-io — COMMENTED** [review]
cool! great start :+1:

**Comment by nj-io** [comment]
wait, why is the mobile navbar gone?

**Comment by SamiSha99** [comment]
I also have the same question, why the mobile navbar has been removed?

Also https://i.imgur.com/shOoLxw.png

???

**Comment by MarlenAw** [comment]
@ionush, @SamiSha99...The navbar is back. Check #14

**Comment by MarlenAw** [comment]
@claireinez, @Karyum please don't merge this pull request

**Pull request merged**
